# Generated by Django 5.1.2 on 2024-10-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('municipality', models.CharField(max_length=100)),
                ('settlement', models.CharField(max_length=100)),
                ('incident_type', models.CharField(choices=[('water', 'Вода'), ('heat', 'Тепло'), ('light', 'Свет'), ('gas', 'Газ')], max_length=20)),
                ('affected_houses', models.IntegerField()),
                ('restoration_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
