# Generated by Django 5.1.2 on 2024-10-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_is_deleted_alter_incident_affected_houses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='is_deleted',
        ),
    ]
