# Generated by Django 5.1.2 on 2024-10-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incident_delete_comment_incident_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='delete_comment',
            new_name='comment',
        ),
    ]
